services:
  mysql-instance:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: 'bookstore_final'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'sa'
      MYSQL_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - bookstore-volume:/var/lib/mysql


  bookstore-api:
    build: .
    ports:
      - 8080:8081
    expose:
      - 8080
    depends_on:
      - mysql-instance

volumes:
  bookstore-volume: